POST {{$dotenv BACKEND_URL}}/products
Authorization: Bearer {{$dotenv USER_ID_TOKEN}}
Content-Type: application/json

{
  "amountAvailable": 100,
  "cost": 100,
  "productName": "Test product"
}

###

GET {{$dotenv BACKEND_URL}}/products

###

GET {{$dotenv BACKEND_URL}}/products/npt1UDoJtKQ1ITPkI9a9

###

PATCH {{$dotenv BACKEND_URL}}/products/npt1UDoJtKQ1ITPkI9a9
Authorization: Bearer {{$dotenv USER_ID_TOKEN}}
Content-Type: application/json

{
  "cost": 75,
  "productName": "Test updated"
}

###

DELETE {{$dotenv BACKEND_URL}}/products/vfkjIE2mhggNWGQnFzq3
Authorization: Bearer {{$dotenv USER_ID_TOKEN}}
