### Create user (new account)
POST {{$dotenv BACKEND_URL}}/users
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "123456",
  "role": "seller",
  "username": "test"
}

### Get user by id
GET {{$dotenv BACKEND_URL}}/users/SBNztwoFRYWeg7lbg5SxT9qxB3Q2
Authorization: Bearer {{$dotenv USER_ID_TOKEN}}

### Update user signed in
PATCH {{$dotenv BACKEND_URL}}/users
Authorization: Bearer {{$dotenv USER_ID_TOKEN}}
Content-Type: application/json

{
  "username": "test"
}

### Delete user signed in
DELETE {{$dotenv BACKEND_URL}}/users
Authorization: Bearer {{$dotenv USER_ID_TOKEN}}
